#############################################################################
# Makefile for building: ex17
# Generated by qmake (2.01a) (Qt 4.8.6) on: Sat Mar 5 23:27:01 2016
# Project:  ex17.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile ex17.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/X11R6/include -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L/usr/X11R6/lib64 -lQtOpenGL -lQtGui -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ex17.cpp \
		ex17viewer.cpp \
		ex17opengl.cpp \
		Object.cpp \
		Cube.cpp \
		Sphere.cpp \
		Teapot.cpp \
		WaveOBJ.cpp \
		Noise.cpp moc_ex17viewer.cpp \
		moc_ex17opengl.cpp \
		qrc_ex17.cpp
OBJECTS       = ex17.o \
		ex17viewer.o \
		ex17opengl.o \
		Object.o \
		Cube.o \
		Sphere.o \
		Teapot.o \
		WaveOBJ.o \
		Noise.o \
		moc_ex17viewer.o \
		moc_ex17opengl.o \
		qrc_ex17.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		ex17.pro
QMAKE_TARGET  = ex17
DESTDIR       = 
TARGET        = ex17

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ex17.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile ex17.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile ex17.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/ex171.0.0 || $(MKDIR) .tmp/ex171.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/ex171.0.0/ && $(COPY_FILE) --parents ex17viewer.h ex17opengl.h Type.h Object.h Cube.h Sphere.h Teapot.h WaveOBJ.h Noise.h .tmp/ex171.0.0/ && $(COPY_FILE) --parents ex17.qrc .tmp/ex171.0.0/ && $(COPY_FILE) --parents ex17.cpp ex17viewer.cpp ex17opengl.cpp Object.cpp Cube.cpp Sphere.cpp Teapot.cpp WaveOBJ.cpp Noise.cpp .tmp/ex171.0.0/ && (cd `dirname .tmp/ex171.0.0` && $(TAR) ex171.0.0.tar ex171.0.0 && $(COMPRESS) ex171.0.0.tar) && $(MOVE) `dirname .tmp/ex171.0.0`/ex171.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ex171.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_ex17viewer.cpp moc_ex17opengl.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ex17viewer.cpp moc_ex17opengl.cpp
moc_ex17viewer.cpp: ex17opengl.h \
		Object.h \
		Type.h \
		ex17viewer.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) ex17viewer.h -o moc_ex17viewer.cpp

moc_ex17opengl.cpp: Object.h \
		Type.h \
		ex17opengl.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) ex17opengl.h -o moc_ex17opengl.cpp

compiler_rcc_make_all: qrc_ex17.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_ex17.cpp
qrc_ex17.cpp: ex17.qrc \
		bunny.obj \
		ex17.frag \
		ex17.vert
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name ex17 ex17.qrc -o qrc_ex17.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

ex17.o: ex17.cpp ex17viewer.h \
		ex17opengl.h \
		Object.h \
		Type.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ex17.o ex17.cpp

ex17viewer.o: ex17viewer.cpp ex17viewer.h \
		ex17opengl.h \
		Object.h \
		Type.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ex17viewer.o ex17viewer.cpp

ex17opengl.o: ex17opengl.cpp ex17opengl.h \
		Object.h \
		Type.h \
		Cube.h \
		WaveOBJ.h \
		Teapot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ex17opengl.o ex17opengl.cpp

Object.o: Object.cpp Object.h \
		Type.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Object.o Object.cpp

Cube.o: Cube.cpp Cube.h \
		Object.h \
		Type.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Cube.o Cube.cpp

Sphere.o: Sphere.cpp Sphere.h \
		Object.h \
		Type.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Sphere.o Sphere.cpp

Teapot.o: Teapot.cpp Teapot.h \
		Object.h \
		Type.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Teapot.o Teapot.cpp

WaveOBJ.o: WaveOBJ.cpp WaveOBJ.h \
		Object.h \
		Type.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WaveOBJ.o WaveOBJ.cpp

Noise.o: Noise.cpp Noise.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Noise.o Noise.cpp

moc_ex17viewer.o: moc_ex17viewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ex17viewer.o moc_ex17viewer.cpp

moc_ex17opengl.o: moc_ex17opengl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ex17opengl.o moc_ex17opengl.cpp

qrc_ex17.o: qrc_ex17.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_ex17.o qrc_ex17.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

